"use client"; 
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState,useEffect, use, } from "react";
import Link from 'next/link';
import { useRouter } from 'next/navigation'
import { getAuth, onAuthStateChanged,signOut,signInWithPopup,GoogleAuthProvider } from "firebase/auth";
import { auth } from "./firebase.js"
const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);


  function handleSignOut(){
    signOut(auth).then(() => {
      setUser(null)
    }).catch((error) => {
      console.log(error);
      
    });
  }


  


  function handleSignin(){
    
    const provider = new GoogleAuthProvider();
    signInWithPopup(auth, provider)
        .then((result) => {
          console.log(result.user.displayName);
          
        }).catch((error) => {
          // Handle Errors here.
          const errorCode = error.code;
          const errorMessage = error.message;
          // The email of the user's account used.
          const email = error.customData.email;
          // The AuthCredential type that was used.
          const credential = GoogleAuthProvider.credentialFromError(error);
          // ...
        });
        }

  useEffect(()=>{
    const  unsubscribe=onAuthStateChanged(auth,(currentUser)=>{
      if(currentUser){
        
        setUser(currentUser)
        
      }else{
        console.log("沒有");
        
      }
    })
    return () => unsubscribe();
  },[setUser])
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
          
          <div className="header_name" onClick={()=>{router.push('/');}}  >
            funliday
          </div>
          <div className="header_member">
            {user ? <div onClick={handleSignOut}>登出</div> : <div onClick={handleSignin}>登入</div>}
          </div>
        </div>
        <hr style={{color:'black',margin:'0',padding:'0',border:'0',height:'1.5px', boxSizing: 'border-box',background: '#999999ff'}}></hr>
        {children}
      </body>
    </html>
  );
}
