"use client"; 
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState,useEffect, use, } from "react";
import Link from 'next/link';
import { useRouter,usePathname } from 'next/navigation'
import { getAuth, onAuthStateChanged,signOut,signInWithPopup,GoogleAuthProvider } from "firebase/auth";
import { auth } from "./firebase.js"
const inter = Inter({ subsets: ["latin"] });
import Image from 'next/image';


/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  const [user, setUser] = useState<any>(null);
  const specialRoute =  /^\/[^\/]+\/trip\/[^\/]+$/.test(pathname);
  const [name,setName]=useState<string|null>('')
  const[userPhoto ,setUserPhoto]=useState<String|null>('')
  const [showSignOut, setShowSignOut] = useState(false);
  function handleSignOut(){
    signOut(auth).then(() => {
      setUser(null)
    }).catch((error) => {
      console.log(error);
      
    });
  }
  function handleSignin(){
    
    const provider = new GoogleAuthProvider();
    signInWithPopup(auth, provider)
        .then((result) => {
          console.log(result.user.displayName);
          
        }).catch((error) => {
          // Handle Errors here.
          const errorCode = error.code;
          const errorMessage = error.message;
          // The email of the user's account used.
          const email = error.customData.email;
          // The AuthCredential type that was used.
          const credential = GoogleAuthProvider.credentialFromError(error);
          // ...
        });
        }

  useEffect(()=>{
    const  unsubscribe=onAuthStateChanged(auth,(currentUser)=>{
      if(currentUser){
        //console.log(currentUser.displayName);
        //console.log(currentUser.photoURL);
        setName(currentUser.displayName)
        setUserPhoto(currentUser.photoURL)
        setUser(currentUser)
        
      }else{
        console.log("沒有");
        
      }
    })
    return () => unsubscribe();
  },[setUser])
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="header">
          <div 
            className="header_name" 
            onClick={()=>{router.push('/trip');}}   
            style={{ marginLeft: specialRoute ? '20px' : '120px' }}
            >
            Cheerliday
          </div>

          {/*
          <div className="header_member" style={{ marginRight: specialRoute ? '20px' : '120px' }}>
            {user ? <div onClick={handleSignOut}>登出</div> : <div onClick={handleSignin}>登入</div>}
          </div>
          */}
          <div>
            {
              user?(
                  <div style={{display:'flex',height:'50px',justifyContent:'center',width:'350px',alignItems: 'center'}}>
              
                  <div 
                      style={{
                        marginLeft:'10PX',
                        height:'35px',
                        width:'35px',
                        borderRadius:'50%', 
                        boxShadow: '0 0 0 2px white, 0 0 0 3px #666666ff',
                        backgroundImage: `url(${userPhoto})`,
                        backgroundPosition: 'center', 
                        backgroundSize: 'cover',
                        }}
                    >    
                  </div>
                  <div  style={{marginLeft:'10px',fontSize:'20PX',fontWeight: '600',color:'#575757ff'}}>{name}，你好！</div>
                  <div style={{display:'flex'}} onClick={handleSignOut}>
                      <Image
                        src="/logout.png"
                        alt="登出"
                        width={20}
                        height={20}
                        style={{marginLeft:'30PX',marginRight:'5px'}}
                      />
                      <div>登出</div>
                  </div>
                </div>
              ):(<div className="header_member" onClick={handleSignin}>登入</div>)
            }
          </div>
        </div>
        <main >{children}</main>
      </body>
    </html>
  );
}

